sudo: required
services:
  - docker
before_install:
  - docker build -t geekhitesh/client-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true geekhitesh/client-test npm test

after_success:
  - docker build -t geekhitesh/multi-client ./client
  - docker build -t geekhitesh/multi-nginx ./nginx
  - docker build -t geekhitesh/multi-server ./server
  - docker build -t geekhitesh/multi-worker ./worker
  # login into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push geekhitesh/multi-client
  - docker push geekhitesh/multi-nginx
  - docker push geekhitesh/multi-server
  - docker push geekhitesh/multi-worker
##new
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multi-docker"
  env: "multi-docker-env"
  bucket-name: "elasticbeanstalk-ap-south-1-518134791710"
  bucket-path: "multi-docker-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"